### ISSUE TITLE
Deploying AMP using alternative method (not apply_amps) breaks SOLR - documentation issue

### ISSUE THREAD

**Issue by dareeos** [Alfresco/alfresco-support-tools#23]
Deploying the AMP using _java -jar alfresco-mmt.jar_ method and following the steps outlined in installation instructions ends up with broken Solr (Tracking failed) after deploying the AMP.

**Test platforms**
Ubuntu 14.04 LTS Minimal install
Alfresco 5.0.3 EE trial, Alfresco 5.1 EE trial

**Steps to reproduce**
1. Install Alfresco
2. Start up, wait for instance to come up
3. Shutdown Alfresco
4. Install the amp using _~/alfresco-one/java/bin/java -jar alfresco-mmt.jar install ~/install/support-tools-1.10.amp ~/alfresco-one/tomcat/webapps/alfresco.war -force -verbose_
5. Delete folders as outlined
6. Start Alfresco again

During bootstrap check catalina.out, the following is logged:
`ERROR [solr.tracker.AbstractTracker] [SolrTrackerScheduler_Worker-3] Tracking failed
 org.alfresco.error.AlfrescoRuntimeException: 03280023 api/solr/aclchangesets return status:404
        at org.alfresco.solr.client.SOLRAPIClient.getAclChangeSets(SOLRAPIClient.java:159)
        at org.alfresco.solr.tracker.AclTracker.checkRepoAndIndexConsistency(AclTracker.java:347)
        at org.alfresco.solr.tracker.AclTracker.trackRepository(AclTracker.java:313)
        at org.alfresco.solr.tracker.AclTracker.doTrack(AclTracker.java:104)
        at org.alfresco.solr.tracker.AbstractTracker.track(AbstractTracker.java:153)
        at org.alfresco.solr.tracker.TrackerJob.execute(TrackerJob.java:47)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)`

You can't login to Alfresco.

**Workaround**
Copy the AMP file to ./amps and run the apply_amps.sh script.

**Cause**
tomcat/webapps/alfresco/* --> folder alfresco needs to be removed as well, not the content of the folder only (documentation error)

**Comment by AntonioSoler** [comment]
Closing this as solved with the change  	8527bac
